arbsol/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import issuetracker.views
from django.contrib.auth import views

urlpatterns = [
    # url(r'^/', 'django.contrib.auth.login', {'template_name':'admin/login.html'}),
    url(r'^$', issuetracker.views.index),
    url(r'^accounts/login/$', issuetracker.views.login_user),
    url(r'^accounts/logout/$', views.logout, {'template_name': 'issuetracker/index.html'}),
    url(r'^accounts/register/$', issuetracker.views.register_user),
    # url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'admin/login.html'}),
    # url(r'^accounts/changepassword/$', 'django.contrib.auth.views.password_change'),
    # url(r'^accounts/profile/$', 'issuetracker.views.index'),
    # url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^issuetracker/', include('issuetracker.urls')),
    url(r'^admin/', admin.site.urls),
]

issuetracker/urls.py
from django.conf.urls import url
from . import views

app_name = 'issuetracker'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^issue/(?P<pk>[0-9]+)/$', views.IssueView.as_view(), name='detail'),
    url(r'^issue/(?P<issue_id>[0-9]+)/$', views.issue, name='detail'),
    url(r'^issue/add/$',views.newissue, name='newissue'),
    url(r'^issue/(?P<issue_id>[0-9]+)/save/$', views.saveissue, name='saveissue'),
    url(r'^issue/(?P<issue_id>[0-9]+)/delete/$', views.deleteissue, name='deleteissue'),
    url(r'^issue/(?P<issue_id>[0-9]+)/undelete/$', views.undeleteissue, name='undeleteissue'),
    url(r'^issue/(?P<issue_id>[0-9]+)/note/add/$', views.newnote, name='newnote'),
    url(r'^deleted/$', views.DeletedView.as_view(), name='deleted')
    # url(r'^nameform/$', views.get_name, name='get_name')
    # url(r'^$', views.index, name='index')
]

issuetracker/models.py
from django.db import models
from django.contrib.auth.models import User


class Issue(models.Model):
    issue_text = models.TextField(verbose_name="Issue")
    user = models.ForeignKey(User)
    resolved = models.BooleanField(default=False)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Date Added')
    pub_modified = models.DateTimeField(auto_now=True, verbose_name='Last Modified')
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.issue_text


class Note(models.Model):
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    user = models.ForeignKey(User)
    note_text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    pub_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.note_text

issuetracker/forms.py
from django import forms
from issuetracker.models import Issue
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)


class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['issue_text']

issuetracker/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.views import generic
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import Issue, Note
from issuetracker.forms import NameForm, IssueForm


from django import template
from issuetracker.models import Issue
register = template.Library()


@register.simple_tag
def active_issue_count():
    return 5 #Issue.objects.filter(active=True).count()




def login_user(request):
    if request.user.is_authenticated():
        messages.add_message(request, messages.ERROR, "You have been logged out")
    logout(request)
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/issuetracker/')
        else:
            messages.add_message(request, messages.ERROR, "Incorrect username or password")
    return render_to_response('issuetracker/login.html', context_instance=RequestContext(request))


def register_user(request):
    logout(request)
    username = password = email = first_name = last_name = ''
    if request.POST:
        if request.POST['password1'] != request.POST['password2']:
            messages.add_message(request, messages.ERROR, "Passwords do not match")
            return render_to_response('issuetracker/register.html', context_instance=RequestContext(request))
        # TODO: Check to make sure username and email are not taken already
        username = request.POST.get('username', None)
        password = request.POST.get('password1', None)
        email = request.POST.get('email', None)
        first_name = request.POST.get('first_name', None)
        last_name = request.POST.get('last_name', None)
        if User.objects.filter(username=username).exists():
            messages.add_message(request, messages.ERROR, "An account with that username already exists.")
        else:
            user = User.objects.create_user(username=username, email=email, password=password, first_name=first_name, last_name=last_name)
            if user is not None:
                messages.add_message(request, messages.SUCCESS, "Your account has been created!")
                if user.is_active:
                    # login(request, user)
                    return HttpResponseRedirect('/accounts/login/')
            else:
                messages.add_message(request, messages.ERROR, "There was an issue creating your account.")
    return render_to_response('issuetracker/register.html', context_instance=RequestContext(request))


def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = IssueForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = IssueForm(instance=Issue.objects.get(pk=2))

    return render(request, 'issuetracker/name.html', {'form': form})


@login_required(login_url='/accounts/login/')
def index(request):
    return HttpResponseRedirect(reverse("issuetracker:index"))


# @login_required(login_url='/accounts/login')
class IndexView(generic.ListView):
    template_name = 'issuetracker/index.html'
    context_object_name = 'issue_list'

    def get_queryset(self):
        # return Issue.objects.filter(resolved=0).order_by('-pub_modified')
        return Issue.objects.filter(active=True).order_by('-pub_modified')


@login_required(login_url='/accounts/login/')
class IssueView(generic.DetailView):
    model = Issue
    template_name = 'issuetracker/detail.html'

@login_required(login_url='/accounts/login/')
def issue(request, issue_id):
    issue = get_object_or_404(Issue, pk=issue_id)
    return render(request, 'issuetracker/detail.html', { 'issue': issue })


class DeletedView(generic.ListView):
    template_name = 'issuetracker/deleted.html'
    context_object_name = 'issue_list'

    def get_queryset(self):
        return Issue.objects.filter(active=False).order_by('-pub_modified')


@login_required(login_url='/accounts/login/')
def newissue(request):
    if request.method == 'POST' and request.POST:
        try:
            issue = Issue()
            issue.user = request.user
            issue.issue_text = request.POST['issue_text']
            if len(issue.issue_text) > 0:
                issue.save()
                messages.add_message(request,messages.SUCCESS, "Issue added successfully")
                return HttpResponseRedirect(reverse('issuetracker:index'))
            else:
                messages.add_message(request,messages.ERROR, "Please enter an issue")
        except:
            messages.add_message(request,messages.WARNING, "Something went wrong")
    return render(request, 'issuetracker/newissue.html')


@login_required(login_url='/accounts/login/')
def deleteissue(request, issue_id):
    issue = get_object_or_404(Issue, pk=issue_id)
    issue.active = False
    issue.save()
    return HttpResponseRedirect(reverse('issuetracker:index'))


@login_required(login_url='/accounts/login/')
def undeleteissue(request, issue_id):
    issue = get_object_or_404(Issue, pk=issue_id)
    issue.active = True
    issue.save()
    return HttpResponseRedirect(reverse('issuetracker:deleted'))


@login_required(login_url='/accounts/login/')
def newnote(request, issue_id):
    issue = get_object_or_404(Issue, pk=issue_id)
    if request.method == 'POST' and request.POST:
        try:
            note = Note()
            note.user = request.user
            note.note_text = request.POST['note_text']
            if len(note.note_text) > 0:
                note.issue = issue
                note.save()
                messages.add_message(request,messages.SUCCESS, "Note added successfully")
                return HttpResponseRedirect(reverse('issuetracker:detail', args=(issue_id,)))
            else:
                messages.add_message(request,messages.ERROR, "Please enter a note")
        except:
            messages.add_message(request,messages.WARNING, "Something went wrong")
    return HttpResponseRedirect(reverse('issuetracker:detail', args=(issue_id,)))


@login_required(login_url='/accounts/login/')
def saveissue(request, issue_id):
    issue = get_object_or_404(Issue, pk=issue_id)
    try:
        issue.issue_text = request.POST['issue_text']
        if 'resolved' not in request.POST:
            issue.resolved = False
        elif request.POST['resolved'] == "on":
            issue.resolved = True
        issue.save()
    except (KeyError, Issue.DoesNotExist):
        messages.add_message(request, messages.ERROR, "You didn't select an issue.")
        return render(request, 'issuetracker/detail.html', { 'issue': issue })
    else:
        # return render(request, 'issuetracker/detail.html', {
        #     'issue': issue,
        #     'success_message': "Issue saved successfully.",
        # })
        messages.add_message(request, messages.SUCCESS, "Issue saved successfully")
        return HttpResponseRedirect(reverse('issuetracker:index'))

# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = 'polls/results.html'
#
# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'polls/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

issuetracker/templates/issuetracker/base.html
{% include "public/header.html" %}
{% include "public/navigation.html" %}
<div class="container">
{% include "public/messages.html" %}

{% if user.is_authenticated %}
    {% block body_block %}{% endblock %}
{% else %}
    <div class="jumbotron">
  <h1>Welcome to the Issue Tracker</h1>
  <p>In order to use the application you must login. If you do not have a username and password contact the administrator to grant you access.</p>
  <p><a class="btn btn-primary btn-lg" href="/accounts/login" role="button">Login</a></p>
</div>
{% endif %}
</div>

</body>
</html>

issuetracker/templates/issuetracker/deleted.html
{% extends 'issuetracker/base.html' %}

{#{% block title %}{{ category_name }}{% endblock %}#}

{% block body_block %}
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Deleted Issues</h3>
            </div>
            <div class="panel-body table-responsive">
            {% if issue_list %}
                <table class="table table-condensed">
                    <thead>
                    <tr>
{#                        <th>ID</th>#}
                        <th>Issue</th>
                        <th>Note Count</th>
                        <th>Last Modified</th>
                        <th style="text-align: center;">Resolved</th>
                        <th style="text-align: right;">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for issue in issue_list %}
                    <tr>
{#                        <td>{{ issue.id }}</td>#}
                        <td><a href="{% url 'issuetracker:detail' issue.id %}">{{ issue.issue_text }}</a></td>
                        <td>{{ issue.note_set.count }}</td>
                        <td>{{ issue.pub_modified }}</td>
                        <td align="center">{% if issue.resolved %}<span class="glyphicon glyphicon-ok text-success"></span>{% else %}<span class="glyphicon glyphicon-remove text-danger"></span>{% endif %}</td>
                        <td align="right"><a class="btn btn-sm btn-success" href="{% url "issuetracker:undeleteissue" issue.id %}">Restore</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No deleted issues are available.</p>
            {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

issuetracker/templates/issuetracker/detail.html
{% extends 'issuetracker/base.html' %}

{#{% block title %}{{ category_name }}{% endblock %}#}

{% block body_block %}
<div class="row">
    <div class="{% if issue.active %}col-sm-6{% else %}col-xs-12{% endif %}">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">{% if issue.active %}Edit Issue{% else %}Issue{% endif %}</h3>
            </div>
            <div class="panel-body">
                <form action="{% url 'issuetracker:saveissue' issue.id %}" method="post">
                    {% csrf_token %}
                <label>Posted by: <span class="text-danger">{{ issue.user.get_full_name }}</span></label>
                {% if issue.active %}
                    <div class="form-group">
                        <label for="issue_text">Issue:</label>
                        <textarea class="form-control" name="issue_text">{{ issue.issue_text }}</textarea>
                    </div>
                    <div class="checkbox">
                        <label>
                          <input type="checkbox" name="resolved"{% if issue.resolved %} checked{% endif %}> Resolved
                        </label>
                    </div>
                    <input class="btn btn-primary btn-block" type="submit" value="Save">
                {% else %}
                    <h4>{{ issue }}</h4>
                    {% if issue.resolved %}<span class="glyphicon glyphicon-ok text-success">&nbsp;</span>Resolved{% else %}<span class="glyphicon glyphicon-remove text-danger">&nbsp;</span>Not Resolved{% endif %}
                {% endif %}
                </form>
            </div>
        </div>
    </div>
    {% if issue.active %}
    <div class="col-sm-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Add Note</h3>
            </div>
            <div class="panel-body">
                <form action="{% url 'issuetracker:newnote' issue.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="note_text">Issue:</label>
                        <textarea class="form-control" name="note_text"></textarea>
                    </div>
                    <input class="btn btn-primary btn-block" type="submit" value="Save">
                </form>
            </div>
        </div>
    </div>
    {% endif %}
</div>
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Notes</h3>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
        {% if issue.note_set.count > 0 %}
        <table class="table table-condensed">
            <thead>
            <tr>
                <th>Issue</th>
                <th>Posted By</th>
                <th>Last Modified</th>
            </tr>
            </thead>
            <tbody>
        {% for note in issue.note_set.all|dictsortreversed:"pub_date" %}
            <tr>
                <td>{{ note.note_text }}</td>
                <td>{{ note.user.get_full_name }}</td>
                <td>{{ note.pub_modified }}</td>
            </tr>
        {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No notes were found for this issue.</p>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

issuetracker/templates/issuetracker/index.html
{% extends 'issuetracker/base.html' %}

{#{% block title %}{{ category_name }}{% endblock %}#}

{% block body_block %}
<div class="row">
    <div class="col-sm-12">
        <a class="btn btn-primary pull-right" href="{% url "issuetracker:newissue" %}">Add Issue</a>
    </div>
</div>
<br />
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Active Issues</h3>
            </div>
            <div class="panel-body table-responsive">
            {% if issue_list %}
                <table class="table table-condensed">
                    <thead>
                    <tr>
{#                        <th>ID</th>#}
                        <th>Issue</th>
                        <th>Posted By</th>
                        <th>Note Count</th>
                        <th>Last Modified</th>
                        <th style="text-align: center;">Resolved</th>
                        <th style="text-align: right;">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for issue in issue_list %}
                    <tr>
{#                        <td>{{ issue.id }}</td>#}
                        <td><a href="{% url 'issuetracker:detail' issue.id %}">{{ issue.issue_text }}</a></td>
                        <td>{{ issue.user.get_full_name }}</td>
                        <td>{{ issue.note_set.count }}</td>
                        <td>{{ issue.pub_modified }}</td>
                        <td align="center">{% if issue.resolved %}<span class="glyphicon glyphicon-ok text-success"></span>{% else %}<span class="glyphicon glyphicon-remove text-danger"></span>{% endif %}</td>
                        <td align="right"><a class="btn btn-sm btn-danger" href="{% url "issuetracker:deleteissue" issue.id %}">Delete</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No issues are available.</p>
            {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

issuetracker/templates/issuetracker/login.html
{% include "public/header.html" %}
{% include "public/navigation.html" %}
<div class="container">
{% include "public/messages.html" %}
    <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Please Login</h3>
        </div>
        <div class="panel-body">
            <div id="login">
                <form name="LoginForm" action="/accounts/login/" method="post">
                {% csrf_token %}
                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}" />
                {% endif %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input class="form-control" type="text" id="username" name="username"  placeholder="Username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input class="form-control" type="password" name="password" id="password" placeholder="Password">
                </div>
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                    <div class="btn-group" role="group">
                        <a href="/accounts/register" type="button" class="btn btn-danger">Register</a>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
</div>

</body>
</html>

issuetracker/templates/issuetracker/name.html
<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

issuetracker/templates/issuetracker/newissue.html
{% extends 'issuetracker/base.html' %}

{#{% block title %}{{ category_name }}{% endblock %}#}

{% block body_block %}
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Add Issue</h3>
    </div>
    <div class="panel-body">
        <form action="{% url 'issuetracker:newissue' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="issue_text">Issue:</label>
                <textarea class="form-control" name="issue_text">{{ issue.issue_text }}</textarea>
            </div>
            <input class="btn btn-primary btn-block" type="submit" value="Save">
        </form>
    </div>
</div>
{% endblock %}

issuetracker/templates/issuetracker/register.html
{% include "public/header.html" %}
{% include "public/navigation.html" %}
<div class="container">
{% include "public/messages.html" %}
    <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Please Register</h3>
        </div>
        <div class="panel-body">
            <div id="register">
                <form name="RegisterForm" action="/accounts/register/" method="post">
                {% csrf_token %}
                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}" />
                {% endif %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input class="form-control" type="text" id="username" name="username"  placeholder="Username">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input class="form-control" type="email" id="email" name="email"  placeholder="email@arbsol.com">
                </div>
                <div class="form-group">
                    <label for="password1">Password</label>
                    <input class="form-control" type="password" name="password1" id="password1" placeholder="Password">
                </div>
                <div class="form-group">
                    <label for="password"2>Verify Password</label>
                    <input class="form-control" type="password" name="password2" id="password2" placeholder="Password">
                </div>
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input class="form-control" type="text" id="first_name" name="first_name"  placeholder="First Name">
                </div>
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input class="form-control" type="text" id="last_name" name="last_name"  placeholder="Last Name">
                </div>
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        <a href="/accounts/login" class="btn btn-primary">Login</a>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="submit" class="btn btn-danger">Register</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
</div>

</body>
</html>